from pathlib import Path

root = Path(r"C:\_IMPACT\prod-support-tools\py\impact_config_suite")
p = root / "core" / "contrib_extractor.py"
text = p.read_text(encoding="utf-8")
orig = text

old_reports = """  4. Builds TWO reports per client + shortcode under
     Documents/impact-support-log/{YYYYMMDD_HHMMSS}_contrib_reports/JATS/:
     (meta-contrib.json stays at <root>; per-doc xml/html stay in each doc folder)
       <client>_<shortcode>_contrib_v<N>.html   PI value + PI position only
       <client>_<shortcode>_elements_v<N>.html  elements + flags only
       <client>_<shortcode>_issues_v<N>.csv     the findings of the contrib report (with contrib_group, contribs)"""

new_reports = """  4. Builds reports per client + shortcode under
     Documents/impact-support-log/{YYYYMMDD_HHMMSS}_contrib_reports/JATS/:
     (meta-contrib.json stays at <root>; per-doc xml/html stay in each doc folder)
       <client>_<shortcode>_contrib_v<N>.html   PI value + PI position only
       <client>_<shortcode>_elements_v<N>.html  elements + flags only (inside contrib-group)
       <client>_<shortcode>_issues_v<N>.csv     the findings of the contrib report (with contrib_group, contribs)
       <client>_<shortcode>_aff_v<N>.html/.csv  aff + author-notes AFTER </contrib-group>
       <client>_aff_unique_v<N>.html            client-wise unique aff patterns (session)"""

if old_reports not in text:
    raise SystemExit("docstring reports block not found")
text = text.replace(old_reports, new_reports, 1)

old_ver_note = """  SCRIPT_VERSION (top of the file) is bumped on every script change. It is in
  the file names (_v9), shown as a header chip and stored in meta-contrib.json:
  a shortcode generated by an older version shows as [update] and is
  regenerated on the next run. Older versioned files stay on disk."""

new_ver_note = """  SCRIPT_VERSION (top of the file) is bumped on every script change. It is in
  the file names (_v10), shown as a header chip and stored in meta-contrib.json:
  a shortcode generated by an older version shows as [update] and is
  regenerated on the next run. Older versioned files stay on disk."""

if old_ver_note not in text:
    raise SystemExit("version note not found")
text = text.replace(old_ver_note, new_ver_note, 1)

marker = "Public suite API (used by tabs/contrib_extractor_tab.py):"
v10_line = """          v10 aff / author-notes AFTER </contrib-group>: separate *_aff_vN.html/.csv
          shortcode rollup + *_aff_unique_vN.html client unique (session); inside
          contrib-group elements report unchanged; logic in core/contrib_aff.py

"""
if marker not in text:
    raise SystemExit("public API marker not found")
if "v10 aff" not in text:
    text = text.replace(marker, v10_line + marker, 1)

text = text.replace(
    "Port of extract_contrib.py SCRIPT_VERSION=9:",
    "Port of extract_contrib.py SCRIPT_VERSION=10:",
    1,
)

old_sv = 'SCRIPT_VERSION = 9               # bump on EVERY script change: goes into file names (_v9) and marks old reports as "update"'
new_sv = 'SCRIPT_VERSION = 10              # bump on EVERY script change: goes into file names (_v10) and marks old reports as "update"'
if old_sv not in text:
    # maybe already bumped
    if "SCRIPT_VERSION = 10" not in text:
        raise SystemExit("SCRIPT_VERSION line not found")
else:
    text = text.replace(old_sv, new_sv, 1)

old_imp = """from core.contrib_phase0 import (
    OUT_COMPARE_HTML,
    OUT_XML_ORIGINAL,
    OUT_XML_ORIGINAL_CLEAN,
    OUT_XML_REGEN,
    OUT_XML_STRIP_PI,
    write_phase0_chain,
)"""
new_imp = """from core.contrib_phase0 import (
    OUT_COMPARE_HTML,
    OUT_XML_ORIGINAL,
    OUT_XML_ORIGINAL_CLEAN,
    OUT_XML_REGEN,
    OUT_XML_STRIP_PI,
    write_phase0_chain,
)
from core import contrib_aff as _contrib_aff"""
if "contrib_aff as _contrib_aff" not in text:
    if old_imp not in text:
        raise SystemExit("phase0 import not found")
    text = text.replace(old_imp, new_imp, 1)

old_reset = '''def reset_session_report_dir() -> None:
    """Clear the session folder so the next batch gets a new timestamp."""
    global _SESSION_REPORT_DIR
    _SESSION_REPORT_DIR = None'''
new_reset = '''def reset_session_report_dir() -> None:
    """Clear the session folder so the next batch gets a new timestamp."""
    global _SESSION_REPORT_DIR
    _SESSION_REPORT_DIR = None
    _contrib_aff.reset_aff_session()'''
if "_contrib_aff.reset_aff_session" not in text:
    if old_reset not in text:
        raise SystemExit("reset_session not found")
    text = text.replace(old_reset, new_reset, 1)

old_row_init = '''        "hits": [],
        "seqs": [],
        "pat": {},
    }'''
new_row_init = '''        "hits": [],
        "seqs": [],
        "pat": {},
        "aff_nodes": [],
        "author_notes_nodes": [],
        "aff_after_count": 0,
        "author_notes_after_count": 0,
    }'''
if '"aff_nodes": []' not in text:
    if old_row_init not in text:
        raise SystemExit("row init not found")
    text = text.replace(old_row_init, new_row_init, 1)

old_read_tail = '''    row["contribs"] = contribs
    row["raws"] = raws
    row["raw_group"] = raw
    row["group_root"] = group_root
    row["src"] = src.name
    row["gaps"] = [analyze(c) for c in contribs]
    n = len(contribs)
    row["xkeys"] = [xref_key(c) for c in contribs]
    row["cmp_cls"] = [(contrib_class(i, n), row["xkeys"][i]) for i in range(n)]
    row["hits"] = [pattern_hits(g) for g in row["gaps"]]
    row["seqs"] = [pi_sequences(h) for h in row["hits"]]
    return row'''

new_read_tail = '''    row["contribs"] = contribs
    row["raws"] = raws
    row["raw_group"] = raw
    row["group_root"] = group_root
    row["src"] = src.name
    row["gaps"] = [analyze(c) for c in contribs]
    n = len(contribs)
    row["xkeys"] = [xref_key(c) for c in contribs]
    row["cmp_cls"] = [(contrib_class(i, n), row["xkeys"][i]) for i in range(n)]
    row["hits"] = [pattern_hits(g) for g in row["gaps"]]
    row["seqs"] = [pi_sequences(h) for h in row["hits"]]
    # Aff / author-notes AFTER last </contrib-group> (separate from elements report)
    try:
        src_text = src.read_text(encoding="utf-8-sig", errors="replace")
    except OSError as e:
        log(f"[WARN] {docid} - could not re-read source for aff: {e}")
        src_text = ""
    _contrib_aff.attach_after_cg_to_row(row, src_text)
    return row'''

if "attach_after_cg_to_row" not in text:
    if old_read_tail not in text:
        raise SystemExit("read_doc tail not found")
    text = text.replace(old_read_tail, new_read_tail, 1)

old_elem_block = '''    inv = build_inventory(good) if good else None
    elements_out = None
    if inv:
        elements_out = build_elements_report(client, shortcode, inv, report_dir)
        log(
            f"[ELEMENTS] {elements_out} "
            f"({len(inv['elems'])} elements, {flagged_count(inv)} flagged)"
        )

    total_issues = 0'''

new_elem_block = '''    inv = build_inventory(good) if good else None
    elements_out = None
    if inv:
        elements_out = build_elements_report(client, shortcode, inv, report_dir)
        log(
            f"[ELEMENTS] {elements_out} "
            f"({len(inv['elems'])} elements, {flagged_count(inv)} flagged)"
        )

    aff_out = None
    aff_csv_out = None
    aff_unique_out = None
    if good:
        aff_inv = _contrib_aff.build_aff_inventory(good)
        aff_out = _contrib_aff.build_aff_report(client, shortcode, aff_inv, report_dir)
        aff_csv_out = _contrib_aff.build_aff_csv(client, shortcode, good, report_dir)
        _contrib_aff.update_client_aff_unique(client, shortcode, good)
        aff_unique_out = _contrib_aff.build_client_aff_unique_report(client, report_dir)
        log(
            f"[AFF] {aff_out} "
            f"(aff={aff_inv['n_aff']}, author-notes={aff_inv['n_notes']}, "
            f"unique_inner={len(aff_inv['aff_inner'])})"
        )
        if aff_csv_out:
            log(f"[AFF CSV] {aff_csv_out}")
        if aff_unique_out:
            log(f"[AFF UNIQUE] {aff_unique_out}")

    total_issues = 0'''

if "build_aff_report" not in text or "aff_out = None" not in text:
    if old_elem_block not in text:
        raise SystemExit("elements block not found")
    text = text.replace(old_elem_block, new_elem_block, 1)

old_paths = '''    path_bits = [f"contrib={path_for_meta(out)}"]
    if elements_out:
        path_bits.append(f"elements={path_for_meta(elements_out)}")
    path_bits.append(f"issues={path_for_meta(csv_out)}")
    log(f"[PATHS] {client}/{shortcode}: " + " | ".join(path_bits))'''

new_paths = '''    path_bits = [f"contrib={path_for_meta(out)}"]
    if elements_out:
        path_bits.append(f"elements={path_for_meta(elements_out)}")
    path_bits.append(f"issues={path_for_meta(csv_out)}")
    if aff_out:
        path_bits.append(f"aff={path_for_meta(aff_out)}")
    if aff_csv_out:
        path_bits.append(f"aff_csv={path_for_meta(aff_csv_out)}")
    if aff_unique_out:
        path_bits.append(f"aff_unique={path_for_meta(aff_unique_out)}")
    log(f"[PATHS] {client}/{shortcode}: " + " | ".join(path_bits))'''

if 'f"aff={path_for_meta(aff_out)}"' not in text:
    if old_paths not in text:
        raise SystemExit("paths block not found")
    text = text.replace(old_paths, new_paths, 1)

old_meta = '''    return {
        "generated_at": now(),
        "version": SCRIPT_VERSION,
        "report": path_for_meta(out),
        "elements_report": path_for_meta(elements_out) if elements_out else None,
        "issues_csv": path_for_meta(csv_out),
        "unique_elements": len(inv["elems"]) if inv else 0,
        "flagged_elements": flagged_count(inv) if inv else 0,'''

new_meta = '''    return {
        "generated_at": now(),
        "version": SCRIPT_VERSION,
        "report": path_for_meta(out),
        "elements_report": path_for_meta(elements_out) if elements_out else None,
        "issues_csv": path_for_meta(csv_out),
        "aff_report": path_for_meta(aff_out) if aff_out else None,
        "aff_csv": path_for_meta(aff_csv_out) if aff_csv_out else None,
        "aff_unique_report": path_for_meta(aff_unique_out) if aff_unique_out else None,
        "unique_elements": len(inv["elems"]) if inv else 0,
        "flagged_elements": flagged_count(inv) if inv else 0,'''

if '"aff_report"' not in text:
    if old_meta not in text:
        raise SystemExit("success meta return not found")
    text = text.replace(old_meta, new_meta, 1)

old_cancel_meta = '''            "report": "",
            "elements_report": None,
            "issues_csv": None,
            "unique_elements": 0,'''
new_cancel_meta = '''            "report": "",
            "elements_report": None,
            "issues_csv": None,
            "aff_report": None,
            "aff_csv": None,
            "aff_unique_report": None,
            "unique_elements": 0,'''
if '"aff_report": None' not in text:
    if old_cancel_meta not in text:
        raise SystemExit("cancel meta not found")
    text = text.replace(old_cancel_meta, new_cancel_meta, 1)

text = text.replace(
    '"""Build per-doc outputs, the contrib report, the element list and the issues csv."""',
    '"""Build per-doc outputs, contrib/elements/aff reports and the issues csv."""',
    1,
)

if text == orig:
    raise SystemExit("no changes applied")
p.write_text(text, encoding="utf-8")
print("patched", p)
print("SCRIPT_VERSION=", [ln.strip() for ln in text.splitlines() if ln.startswith("SCRIPT_VERSION =")][0])
