"""
extract_contrib.py

For every document in documents.json (using meta.json for client / shortcode):

  1. Finds the document XML inside its folder (e.g. JATS/<docid>/)
  2. Extracts the <contrib-group> XML        -> <folder>/contrib_group.xml
  3. Builds an HTML preview of all contribs   -> <folder>/contrib_preview.html
  4. Builds TWO reports per client + shortcode (in <root>/contrib_reports/JATS/):
       <client>_<shortcode>_contrib_v<N>.html   PI value + PI position only
       <client>_<shortcode>_elements_v<N>.html  elements + flags only
       <client>_<shortcode>_issues_v<N>.csv     the findings of the contrib report

Version
-------
  SCRIPT_VERSION (top of the file) is bumped on every script change. It is in
  the file names (_v8), shown as a header chip and stored in meta-contrib.json:
  a shortcode generated by an older version shows as [update] and is
  regenerated on the next run. Older versioned files stay on disk.
      v1  contrib-group extraction, HTML preview (pistart text restored), report per shortcode
      v2  Raw XML toggle, Docid column, sticky header, all-contrib consistency check
      v3  pattern statistics, JATS-only run + meta-contrib.json + pauses,
          1/2/3+ column rule, xref groups
      v4  versioned file names, element inventory
      v5  (element list hid the default elements - withdrawn)
      v6  element list shows ALL elements again
      v7  (element chips inside the contrib report - withdrawn)
      v8  two clearly separated reports; xref groups 0/1/2/3+ with first /
          last-before / last xref roles; files-to-fix table, pattern previews,
          issues.csv, "only files with issues" filter; element flags

1. CONTRIB REPORT  (PI attr value + PI position, nothing else)
--------------------------------------------------------------
  Columns: File ID | Docid | First contrib | Last before | Last contrib
  Which contrib goes in which column (by the number of contribs):
      1 contrib    -> Last contrib only            (First, Last before = "-")
      2 contribs   -> Last before + Last contrib   (First = "-")
      3+ contribs  -> First, Last before (2nd from the end), Last contrib

  Sections (top to bottom)
    Files to fix        one row per off-pattern file: column, xref group, kind
                        (PI attr value / PI position), what differs
    Statistics          patterns per column and xref group (see below), each
                        pattern card has a preview of a sample file with the
                        differing pistarts in red
    PI check on all contribs   the same "same value, same position" idea for
                        EVERY contrib (middle contribs too)
    File table          preview (pistart text restored) or Raw XML (toggle),
                        pattern-N tags, "only files with issues" filter

  xref groups: files are split by the number of <xref> in the contrib:
      xref 0 | xref 1 | xref 2 | xref 3+
  and only three xrefs are looked at, named by role like the contribs:
      1 xref  -> last            2 xrefs -> last-before, last
      3+ xrefs -> first, last-before, last   (middle xrefs are skipped)
  The pistart after an xref is written as "after first xref",
  "after last-before xref", "after last xref". The middle xrefs are only
  covered by the "PI check on all contribs".

  Patterns: every file is reduced to two patterns per column
      PI attr value : the ordered pistart values of that contrib
      PI position   : the ordered places where a pistart sits
  Inside each xref group the files get pattern-N  <files with it>/<files in
  the group>; pattern-1 is the most common. Other patterns list their files
  and say what differs: differs / missing / extra.

  Preview rule: <?pistart xml:space=",&#x00A0;"?> -> the attribute value is put
  back as real text at that position. Other PIs and comments are ignored.

  PI check on all contribs: a "position" is a gap inside a <contrib>. The
  value of a position is the pistart text sitting there. Contribs are only
  compared with contribs of the same class (last / last before / other) and
  the same xref group; where a position has more than one value, the most
  common one is expected and the others are flagged (red = different,
  warning = missing). Middle xrefs are compared here too.

2. ELEMENT LIST  (elements + flags, no pistart values)
------------------------------------------------------
  Every element name found in the <contrib-group>s of the shortcode, nothing
  excluded: files containing it, occurrences, per-contrib counts
  (e.g. xref 0: 12 . 1: 340 . 2: 210), parents, attributes (values + counts).
  Flags: partial (not in every file - the files are listed), rare (in
  RARE_MAX files or fewer), repeats (more than one per contrib), empty (no text
  and no child element, e.g. an <email> that only holds a PI), rare attribute
  values. Other processing instructions (attributepistart, PageID ...) and
  comments are listed as flags only (files + occurrences, no values).

Selection + meta-contrib.json
-----------------------------
  Only documents whose meta.json "dtd" is JATS are used (RUN_DTD below; BITS
  is ignored). Before anything runs an overview lists Clients -> Shortcodes
  with doc counts and whether each is already filled (generated) or not.
  You are then asked for the client(s) and the shortcode(s):
      Enter  = every shortcode that is not filled or has new docs   (default)
      1,3    = the numbers / names you type (asks before redoing a filled one)
      all    = regenerate everything for the chosen client(s)

  Every generated shortcode is recorded in root/meta-contrib.json so it is
  not generated again:

      { "JATS": { "LWW": { "INF": {
            "generated_at": "...", "version": 8,
            "report": "contrib_reports/JATS/LWW_INF_contrib_v8.html",
            "elements_report": "...", "issues_csv": "...",
            "documents": 45, "failed": 0, "off_pattern_files": 3,
            "consistency_issues": 4,
            "docids": { "<docid>": {"file-id": "...", "contribs": 18, "status": "ok"}, ... }
      } } } }

  Run order: strictly one shortcode at a time (reports written and recorded in
  meta-contrib.json), then a pause, then the next shortcode of that client.
  When a client is complete there is a (longer) pause and the next client
  starts. Pauses are asked once (Enter = defaults DELAY_SHORTCODE_SEC /
  DELAY_CLIENT_SEC). Ctrl+C stops cleanly; finished shortcodes stay recorded.
  A shortcode counts as "update" when meta.json has docids that are not
  recorded yet, or when it was generated by an older SCRIPT_VERSION.
  Regenerating a shortcode always rebuilds its whole report.

Expected layout:
    root/documents.json
    root/meta.json
    root/meta-contrib.json      (created / updated by this script)
    root/<folder from documents.json>/...xml
    root/contrib_reports/JATS/

Usage:
    python extract_contrib.py
    (then enter the project root folder, client and shortcode when prompted)

Requires Python 3.10+. No extra packages.
"""

import csv
import difflib
import html
import json
import os
import re
import time
import xml.etree.ElementTree as ET
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from datetime import datetime
from html.entities import name2codepoint
from pathlib import Path

DOCS_NAME = "documents.json"
META_NAME = "meta.json"
DONE_NAME = "meta-contrib.json"   # what has already been generated
REPORT_DIR = "contrib_reports"
RUN_DTD = "JATS"                 # only this DTD is processed
SCRIPT_VERSION = 8               # bump on EVERY script change: goes into file names (_v8) and marks old reports as "update"
RARE_MAX = 2                     # element list: "rare" = in this many files or fewer
DELAY_SHORTCODE_SEC = 5          # default pause between two shortcodes of one client
DELAY_CLIENT_SEC = 10            # default pause when the next shortcode belongs to another client
OUT_XML = "contrib_group.xml"
OUT_HTML = "contrib_preview.html"

# xml files that must never be treated as the document xml
SKIP_XML = {"impact_config.xml", OUT_XML}

HIGHLIGHT_PI = True  # yellow background on text restored from pistart

CONTRIB_GROUP_RE = re.compile(r"<contrib-group\b.*?</contrib-group>", re.S)
CONTRIB_RE = re.compile(r"<contrib(?=[\s>]).*?</contrib>", re.S)
NAMED_ENTITY_RE = re.compile(r"&([A-Za-z][A-Za-z0-9]*);")
PI_VALUE_RE = re.compile(r"""xml:space\s*=\s*(?:"([^"]*)"|'([^']*)')""")
WS_RE = re.compile(r"[ \t\r\n]+")  # NOTE: does not match nbsp on purpose
XML_ENTITIES = {"amp", "lt", "gt", "quot", "apos"}

NS_DECLS = (
    'xmlns:xlink="http://www.w3.org/1999/xlink" '
    'xmlns:mml="http://www.w3.org/1998/Math/MathML" '
    'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"'
)

INLINE_TAGS = {"sup": "sup", "sub": "sub", "italic": "i", "bold": "b"}

PI = ET.ProcessingInstruction


# ----------------------------------------------------------------- io helpers

def load_json(path: Path) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def safe_name(s: str) -> str:
    return re.sub(r"[^\w.-]+", "_", s.strip()) or "unknown"


# ------------------------------------------------------------ locating files

def doc_folder(base: Path, docid: str, item: dict, meta: dict) -> Path:
    folder = item.get("folder")
    if folder:
        return base / folder
    return base / meta.get("dtd", "") / docid


def candidate_xml_files(base: Path, folder: Path, item: dict) -> list[Path]:
    found: list[Path] = []

    def add(p: Path):
        if (
            p.suffix.lower() == ".xml"
            and p.name.lower() not in SKIP_XML
            and p.exists()
            and p not in found
        ):
            found.append(p)

    # 1) anything documents.json already knows about
    for rel in (item.get("files") or {}).values():
        if isinstance(rel, str):
            add(base / rel)

    # 2) any other xml sitting in the folder
    if folder.is_dir():
        for p in sorted(folder.glob("*.xml")):
            add(p)

    return found


def extract_contrib_groups(folder: Path, base: Path, item: dict):
    """Return (source_path, raw_contrib_group_xml) or (None, None)."""
    for p in candidate_xml_files(base, folder, item):
        text = p.read_text(encoding="utf-8-sig", errors="replace")
        groups = CONTRIB_GROUP_RE.findall(text)
        if groups:
            return p, "\n\n".join(groups)
    return None, None


# ------------------------------------------------------------------- parsing

def _fix_entity(m: re.Match) -> str:
    name = m.group(1)
    if name in XML_ENTITIES:
        return m.group(0)
    cp = name2codepoint.get(name)
    # unknown named entity (DTD not loaded) -> keep it visible, but well-formed
    return chr(cp) if cp else f"&amp;{name};"


def parse_group(group_xml: str) -> ET.Element:
    """Parse the extracted <contrib-group> text; returns a synthetic <root> wrapper."""
    wrapped = f"<root {NS_DECLS}>{NAMED_ENTITY_RE.sub(_fix_entity, group_xml)}</root>"
    # insert_pis=True keeps <?pistart ...?> in the tree (ElementTree drops them otherwise)
    parser = ET.XMLParser(target=ET.TreeBuilder(insert_pis=True))
    return ET.fromstring(wrapped, parser=parser)


def tidy_raw(raw: str) -> str:
    """Remove the source indentation so each raw <contrib> reads from column 0."""
    lines = raw.split("\n")
    rest = [l for l in lines[1:] if l.strip()]
    indent = min((len(l) - len(l.lstrip(" \t")) for l in rest), default=0)
    out = [lines[0]] + [l[indent:] if l.strip() else "" for l in lines[1:]]
    return "\n".join(out).replace("\t", "  ")


def raw_contribs(group_xml: str) -> list[str]:
    return [tidy_raw(m) for m in CONTRIB_RE.findall(group_xml)]


def local(tag: str) -> str:
    return tag.rsplit("}", 1)[-1]


def pi_value(pi: ET.Element) -> str | None:
    """Text carried by a <?pistart xml:space="..."?>, or None for any other PI."""
    data = (pi.text or "").strip()
    if not data or data.split(None, 1)[0] != "pistart":
        return None
    m = PI_VALUE_RE.search(data)
    if not m:
        return None
    raw = m.group(1) if m.group(1) is not None else m.group(2)
    return html.unescape(raw)  # &#x00A0; -> nbsp (parser does not decode PI data)


# ----------------------------------------------------------- consistency check

@dataclass
class Gap:
    # (path, prev sibling, next sibling, occurrence); gaps right after an <xref>
    # of a contrib use (path, "xref@<role>", "", 0) instead - see xref_role()
    key: tuple
    value: str                 # concatenated pistart text at this position
    pis: list = field(default_factory=list)   # the PI elements sitting here
    parent: ET.Element | None = None
    before: ET.Element | None = None          # real child that follows (None = end)
    xref_i: int | None = None  # index of the <xref> directly before this gap (contrib level)


@dataclass
class Ctx:
    """Where to draw red marks while rendering one document."""
    pi_bad: dict = field(default_factory=dict)        # id(pi element) -> tooltip
    miss_before: dict = field(default_factory=dict)   # id(child) -> [tooltip]
    miss_end: dict = field(default_factory=dict)      # id(parent) -> [tooltip]


def xref_role(i: int, n: int) -> str:
    """Role of xref number i (0-based) of n: same idea as the contrib columns."""
    if i == n - 1:
        return "last"
    if i == n - 2:
        return "last-before"
    if i == 0:
        return "first"
    return "middle"


def analyze(contrib: ET.Element) -> list[Gap]:
    gaps: list[Gap] = []
    occ: Counter = Counter()

    def walk(el: ET.Element, path: str):
        prev = "^"
        pis: list = []
        vals: list = []
        xi = -1  # index of the last <xref> seen at contrib level

        def close(nxt: str, before):
            base = (path, prev, nxt)
            key = base + (occ[base],)
            occ[base] += 1
            xr = xi if (path == "contrib" and prev == "xref") else None
            gaps.append(Gap(key, "".join(vals), list(pis), el, before, xr))

        for kid in el:
            if kid.tag is PI:
                v = pi_value(kid)
                if v is not None:
                    pis.append(kid)
                    vals.append(v)
                continue
            if not isinstance(kid.tag, str):
                continue
            tag = local(kid.tag)
            close(tag, kid)
            if path == "contrib" and tag == "xref":
                xi += 1
            pis, vals, prev = [], [], tag
            walk(kid, f"{path}/{tag}")
        close("$", None)

    walk(contrib, "contrib")
    n_x = sum(1 for k in contrib if isinstance(k.tag, str) and local(k.tag) == "xref")
    for g in gaps:
        if g.xref_i is not None:
            g.key = ("contrib", "xref@" + xref_role(g.xref_i, n_x), "", 0)
    return gaps


def xref_key(contrib: ET.Element) -> int:
    """xref group of a contrib: 0, 1, 2 or 3 (= three or more xrefs)."""
    n = sum(1 for k in contrib if isinstance(k.tag, str) and local(k.tag) == "xref")
    return min(n, 3)


def xref_label(key: int) -> str:
    return "xref 3+" if key >= 3 else f"xref {key}"


def contrib_class(i: int, n: int) -> str:
    """last / last before / other - same idea as the report columns."""
    if i == n - 1:
        return "last"
    if i == n - 2:
        return "before"
    return "other"


CLASS_LABEL = {"last": "last", "before": "last before", "other": "other"}


def expected_values(items) -> dict:
    """
    items: (class key, gaps of one contrib). Returns
    (class key, position) -> most common value, only where the values disagree.
    """
    counts: dict = defaultdict(Counter)
    for cls, gaps in items:
        for g in gaps:
            counts[(cls, g.key)][g.value] += 1
    return {k: c.most_common(1)[0][0] for k, c in counts.items() if len(c) > 1}


def vis(v: str) -> str:
    return v.replace("\xa0", "<nbsp>")


def pos_label(key: tuple) -> str:
    path, prev, nxt = key[0], key[1], key[2]
    if prev.startswith("xref@"):
        return f"after {prev[5:]} xref"
    a = "start" if prev == "^" else prev
    b = "end" if nxt == "$" else nxt
    return f"{path} [{a} -> {b}]"


def build_ctx(gap_lists, classes, expected: dict):
    """Return (Ctx for rendering, list of issue dicts) for one document."""
    ctx, issues = Ctx(), []
    for n, (gaps, cls) in enumerate(zip(gap_lists, classes), 1):
        for g in gaps:
            exp = expected.get((cls, g.key))
            if exp is None or g.value == exp:
                continue
            if g.value == "":
                kind, what = "missing", f'expected "{vis(exp)}", found nothing'
            elif exp == "":
                kind, what = "unexpected", f'expected nothing, found "{vis(g.value)}"'
            else:
                kind, what = "different", f'expected "{vis(exp)}", found "{vis(g.value)}"'
            text = f"{pos_label(g.key)} ({CLASS_LABEL[cls[0]]}, {xref_label(cls[1])}): {what}"
            issues.append({"n": n, "kind": kind, "text": text})
            if g.pis:
                for p in g.pis:
                    ctx.pi_bad[id(p)] = text
            elif g.before is not None:
                ctx.miss_before.setdefault(id(g.before), []).append(text)
            else:
                ctx.miss_end.setdefault(id(g.parent), []).append(text)
    return ctx, issues


# ----------------------------------------------------- pattern statistics

ROLES = [("first", "First contrib"), ("before", "Last before"), ("last", "Last contrib")]
KINDS = [("attr", "PI attr value"), ("pos", "PI position")]


def role_index(n: int, role: str):
    """
    Index of the contrib shown in a report column (None = no contrib there).
        n == 1 : only "last"
        n == 2 : "before" (index 0) + "last" (index 1)
        n >= 3 : first (0), before (n-2), last (n-1)
    """
    if role == "first":
        return 0 if n >= 3 else None
    if role == "before":
        return n - 2 if n >= 2 else None
    return n - 1 if n >= 1 else None


def pos_short(key: tuple) -> str:
    path, prev, nxt = key[0], key[1], key[2]
    if prev.startswith("xref@"):
        return f"after {prev[5:]} xref"
    if path.startswith("contrib/"):
        path = path[len("contrib/"):]
    a = "start" if prev == "^" else prev
    b = "end" if nxt == "$" else nxt
    return f"{path} [{a} -> {b}]"


def pattern_hits(gaps: list) -> list:
    """Gaps that carry a pistart and take part in the patterns (middle xrefs are skipped)."""
    return [g for g in gaps if g.pis and g.key[1] != "xref@middle"]


def pi_sequences(hits: list) -> dict:
    return {
        "attr": tuple(g.value for g in hits),
        "pos": tuple(pos_short(g.key) for g in hits),
    }


def tok_val(v: str) -> str:
    return v.replace("\xa0", "[nbsp]").replace(" ", "\u00b7") or "(empty)"


def tok(kind: str, x: str) -> str:
    if kind == "attr":
        return f'<code class="tok">{esc(tok_val(x))}</code>'
    return f'<code class="tok pos">{esc(x)}</code>'


def tok_plain(kind: str, x: str) -> str:
    return f"'{tok_val(x)}'" if kind == "attr" else x


def seq_diff(base: tuple, seq: tuple, kind: str):
    """Tokens of `seq` that differ from `base`, plus readable lines (html, plain)."""
    bad: set = set()
    html_l: list = []
    plain: list = []
    if len(base) == len(seq):  # same length: compare slot by slot (clearest for separators)
        for j, (x, y) in enumerate(zip(base, seq)):
            if x != y:
                bad.add(j)
                html_l.append(
                    f'<b class="k differs">differs</b> #{j + 1} expected {tok(kind, x)}, found {tok(kind, y)}'
                )
                plain.append(f"differs #{j + 1} expected {tok_plain(kind, x)}, found {tok_plain(kind, y)}")
        return bad, html_l, plain
    sm = difflib.SequenceMatcher(None, base, seq, autojunk=False)
    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag == "equal":
            continue
        exp = " ".join(tok(kind, x) for x in base[i1:i2])
        got = " ".join(tok(kind, x) for x in seq[j1:j2])
        pexp = " ".join(tok_plain(kind, x) for x in base[i1:i2])
        pgot = " ".join(tok_plain(kind, x) for x in seq[j1:j2])
        if tag == "replace":
            html_l.append(f'<b class="k differs">differs</b> expected {exp}, found {got}')
            plain.append(f"differs expected {pexp}, found {pgot}")
            bad.update(range(j1, j2))
        elif tag == "delete":
            html_l.append(f'<b class="k missing">missing</b> {exp}')
            plain.append(f"missing {pexp}")
        else:
            html_l.append(f'<b class="k extra">extra</b> {got}')
            plain.append(f"extra {pgot}")
            bad.update(range(j1, j2))
    return bad, html_l, plain


def build_stats(rows: list[dict]) -> dict:
    """Per column and kind: files split by xref group, then grouped by pattern."""
    total = len(rows)
    cards = {}
    for role, _ in ROLES:
        for kind, _ in KINDS:
            by_x: dict = {}
            na = []
            for r in rows:
                i = role_index(len(r["contribs"]), role)
                if i is None:
                    na.append(r)
                    r["pat"][(role, kind)] = None
                    r["xk"][role] = None
                    continue
                xk = r["xkeys"][i]
                r["xk"][role] = xk
                by_x.setdefault(xk, {}).setdefault(r["seqs"][i][kind], []).append(r)
            subgroups = []
            for xk in sorted(by_x):
                ordered = sorted(by_x[xk].items(), key=lambda kv: -len(kv[1]))  # stable on ties
                base = ordered[0][0]
                patterns = []
                for n, (seq, rs) in enumerate(ordered, 1):
                    for r in rs:
                        r["pat"][(role, kind)] = n
                    p = {"n": n, "seq": seq, "rows": rs, "bad": set(), "diff_html": [], "diff_plain": []}
                    if n > 1:
                        p["bad"], p["diff_html"], p["diff_plain"] = seq_diff(base, seq, kind)
                    patterns.append(p)
                subgroups.append(
                    {
                        "xk": xk,
                        "files": sum(len(p["rows"]) for p in patterns),
                        "patterns": patterns,
                        "base": base,
                    }
                )
            cards[(role, kind)] = {"subgroups": subgroups, "na": na}
    return {"total": total, "cards": cards}


def off_pattern_rows(rows: list[dict]) -> list[dict]:
    return [r for r in rows if any(n not in (None, 1) for n in r["pat"].values())]


def row_id(docid: str) -> str:
    return "row-" + safe_name(docid)


def file_rows(rows: list[dict]) -> str:
    return "".join(
        f'<div class="frow"><a href="#{esc(row_id(r["docid"]))}">{esc(r["file_id"] or r["docid"])}</a>'
        f'<span class="did">{esc(r["docid"])}</span></div>'
        for r in sorted(rows, key=lambda r: (r["file_id"] or r["docid"]).lower())
    )


def files_details(rows: list[dict], open_: bool) -> str:
    s = "" if len(rows) == 1 else "s"
    return (
        f'<details{" open" if open_ else ""}><summary>{len(rows)} file{s}</summary>'
        f"{file_rows(rows)}</details>"
    )


def sample_preview(role: str, p: dict) -> str:
    """Preview of the first file of a pattern, differing pistarts in red."""
    r = p["rows"][0]
    i = role_index(len(r["contribs"]), role)
    hits = r["hits"][i]
    ctx = Ctx()
    for j in p["bad"]:
        if j < len(hits):
            for pi in hits[j].pis:
                ctx.pi_bad[id(pi)] = "differs from pattern-1"
    who = esc(r["file_id"] or r["docid"])
    return f'<div class="pv"><span class="pv-l">preview - {who}</span>{render(r["contribs"][i], ctx)}</div>'


def render_card(role: str, kind: str, card: dict, total: int) -> str:
    out = []
    for sg in card["subgroups"]:
        size = sg["files"]
        body = []
        for p in sg["patterns"]:
            n, rs = p["n"], p["rows"]
            minor = n > 1
            items = "".join(
                f'<li class="{"bad" if i in p["bad"] else ""}">{tok(kind, x)}</li>'
                for i, x in enumerate(p["seq"])
            ) or '<li class="none">(no pistart)</li>'
            diff_html = "".join(f"<div>{d}</div>" for d in p["diff_html"])
            label = "differs from pattern-1" if minor else "most common"
            body.append(
                f'<div class="pat{" minor" if minor else ""}">'
                f'<div class="pat-h"><b>pattern-{n}</b><span class="cnt">{len(rs)}/{size}</span>'
                f'<span class="pct">{len(rs) / size * 100:.1f}%</span>'
                f'<span class="lbl">{label}</span></div>'
                f'<ol class="seq">{items}</ol>'
                + (f'<div class="diff">{diff_html}</div>' if diff_html else "")
                + sample_preview(role, p)
                + files_details(rs, open_=minor)
                + "</div>"
            )
        out.append(
            '<div class="xg"><div class="xg-h">'
            f'<b>{esc(xref_label(sg["xk"]))}</b><span class="cnt">{size}/{total} files</span></div>'
            + "".join(body)
            + "</div>"
        )
    na = card["na"]
    if na:
        out.append(
            '<div class="pat na"><div class="pat-h"><b>n/a</b>'
            f'<span class="cnt">{len(na)}/{total}</span>'
            '<span class="lbl">no contrib at this index</span></div>'
            + files_details(na, open_=False)
            + "</div>"
        )
    return "".join(out) or '<div class="none">-</div>'


def stats_html(stats: dict | None) -> str:
    if not stats:
        return ""
    total = stats["total"]
    head = "".join(f"<th>{label}</th>" for _, label in ROLES)
    rows = ""
    for kind, klabel in KINDS:
        tds = "".join(
            f'<td>{render_card(role, kind, stats["cards"][(role, kind)], total)}</td>'
            for role, _ in ROLES
        )
        rows += f'<tr><th class="rl">{klabel}</th>{tds}</tr>'
    return (
        '<details class="stats" open><summary>Statistics - PI attr value and PI position patterns '
        '<span class="sub">pattern-N &nbsp;files with it / files in its xref group &nbsp;&middot;&nbsp; '
        "<code class=\"tok\">\u00b7</code> = space, <code class=\"tok\">[nbsp]</code> = non-breaking space"
        "</span></summary>"
        '<div class="legend" style="margin:8px 12px 0">Which contrib is in which column: '
        "1 contrib = Last &middot; 2 contribs = Last before + Last &middot; "
        "3+ contribs = First, Last before, Last.<br>"
        "Files are split by xref count: <b>xref 0</b>, <b>xref 1</b>, <b>xref 2</b>, <b>xref 3+</b>. "
        "Only the first, last-before and last xref are looked at (\u201cafter first xref\u201d, "
        "\u201cafter last-before xref\u201d, \u201cafter last xref\u201d); middle xrefs are skipped here and "
        "covered by the check on all contribs. "
        f"A pattern is compared only inside its xref group (group header = files in group / {total} overall). "
        "The preview under each pattern is a sample file, differing pistarts in red."
        "</div>"
        f'<table class="stat"><tr><th></th>{head}</tr>{rows}</table></details>'
    )


def fix_entries(stats: dict | None) -> list:
    """Every off-pattern finding: one entry per file x column x kind."""
    out: list = []
    if not stats:
        return out
    role_order = [label for _, label in ROLES]
    for role, rlabel in ROLES:
        for kind, klabel in KINDS:
            for sg in stats["cards"][(role, kind)]["subgroups"]:
                for p in sg["patterns"]:
                    if p["n"] == 1:
                        continue
                    for r in p["rows"]:
                        out.append(
                            {
                                "row": r,
                                "role": rlabel,
                                "xref": xref_label(sg["xk"]),
                                "kind": klabel,
                                "pattern": p["n"],
                                "html": p["diff_html"],
                                "plain": p["diff_plain"],
                            }
                        )
    out.sort(
        key=lambda e: (
            (e["row"]["file_id"] or e["row"]["docid"]).lower(),
            role_order.index(e["role"]),
            e["kind"],
        )
    )
    return out


def fix_html(entries: list) -> str:
    if not entries:
        return (
            '<div class="okbox">Files to fix: none - every file follows the most common '
            "PI attr value and PI position pattern of its xref group.</div>"
        )
    n_files = len({e["row"]["docid"] for e in entries})
    rows = "".join(
        f'<tr><td class="fid"><a href="#{esc(row_id(e["row"]["docid"]))}">'
        f'{esc(e["row"]["file_id"] or e["row"]["docid"])}</a></td>'
        f'<td class="docid">{esc(e["row"]["docid"])}</td>'
        f'<td>{esc(e["role"])}</td><td>{esc(e["xref"])}</td><td>{esc(e["kind"])}</td>'
        f'<td>pattern-{e["pattern"]}</td><td class="det">{"<br>".join(e["html"])}</td></tr>'
        for e in entries
    )
    return (
        f'<details class="stats" open><summary>Files to fix - {len(entries)} finding(s) in {n_files} file(s) '
        '<span class="sub">off-pattern PI attr value / PI position, by column</span></summary>'
        '<table class="fix"><tr><th>File ID</th><th>Docid</th><th>Column</th><th>xref group</th>'
        "<th>Kind</th><th>Pattern</th><th>What differs (vs pattern-1)</th></tr>"
        f"{rows}</table></details>"
    )


def allcheck_html(rows: list[dict]) -> str:
    """The 'same value, same position' check over EVERY contrib (middle contribs too)."""
    items = [(r, i) for r in rows for i in r["issues"]]
    if not items:
        return (
            '<details class="stats"><summary>PI check on all contribs '
            '<span class="sub">no inconsistencies</span></summary></details>'
        )
    shown = items[:300]
    trs = "".join(
        f'<tr><td class="fid"><a href="#{esc(row_id(r["docid"]))}">{esc(r["file_id"] or r["docid"])}</a></td>'
        f'<td>#{i["n"]} of {len(r["contribs"])}</td><td class="det">{esc(i["text"])}</td></tr>'
        for r, i in shown
    )
    more = f"<div class='legend' style='margin:0 12px 12px'>... +{len(items) - 300} more (see the csv)</div>" if len(items) > 300 else ""
    return (
        f'<details class="stats" open><summary>PI check on all contribs - {len(items)} issue(s) '
        '<span class="sub">same value, same position, compared with contribs of the same class and xref group '
        "(middle contribs and middle xrefs included)</span></summary>"
        '<table class="fix"><tr><th>File ID</th><th>Contrib</th><th>Issue</th></tr>'
        f"{trs}</table>{more}</details>"
    )


def na_title(n: int) -> str:
    if n == 1:
        return "1 contrib - counted as Last contrib"
    return f"{n} contribs - counted as Last before + Last contrib"


def cell_tags(r: dict, role: str) -> str:
    out = []
    xk = r["xk"].get(role)
    if xk is not None:
        out.append(f'<span class="tag xref" title="xref group">{esc(xref_label(xk))}</span>')
    for kind, label in (("attr", "attr"), ("pos", "pos")):
        n = r["pat"].get((role, kind))
        if n is None:
            continue
        cls = "tag" if n == 1 else "tag bad"
        full = dict(KINDS)[kind]
        out.append(f'<span class="{cls}" title="{full} pattern (inside the xref group)">{label}: pattern-{n}</span>')
    return f'<div class="tags">{"".join(out)}</div>' if out else ""


# ------------------------------------------------------- element list (separate report)

NS_PREFIX = {
    "http://www.w3.org/1999/xlink": "xlink",
    "http://www.w3.org/1998/Math/MathML": "mml",
    "http://www.w3.org/2001/XMLSchema-instance": "xsi",
    "http://www.w3.org/XML/1998/namespace": "xml",
}


def attr_label(key: str) -> str:
    if key.startswith("{"):
        ns, _, name = key[1:].partition("}")
        return f"{NS_PREFIX.get(ns, 'ns')}:{name}"
    return key


def build_inventory(rows: list[dict]) -> dict:
    """Unique element names (+ attributes, parents, per-contrib counts, emptiness) and PI targets."""
    elems: dict = {}
    pis: dict = {}
    comments = {"files": set(), "occ": 0}
    n_contribs = 0

    def entry(name: str) -> dict:
        return elems.setdefault(
            name,
            {
                "files": set(),
                "occ": 0,
                "parents": Counter(),
                "attrs": defaultdict(Counter),
                "per": Counter(),
                "empty": 0,
            },
        )

    def walk(el: ET.Element, parent: str, docid: str):
        for kid in el:
            if kid.tag is PI:
                data = (kid.text or "").strip()
                target = data.split(None, 1)[0] if data else "(empty)"
                e = pis.setdefault(target, {"files": set(), "occ": 0})
                e["files"].add(docid)
                e["occ"] += 1
                continue
            if not isinstance(kid.tag, str):
                continue
            name = local(kid.tag)
            e = entry(name)
            e["files"].add(docid)
            e["occ"] += 1
            e["parents"][parent] += 1
            for k, v in kid.attrib.items():
                e["attrs"][attr_label(k)][v] += 1
            has_child = any(isinstance(c.tag, str) for c in kid)
            has_text = bool((kid.text or "").strip()) or any((c.tail or "").strip() for c in kid)
            if not has_child and not has_text:
                e["empty"] += 1
            walk(kid, name, docid)

    for r in rows:
        walk(r["group_root"], "(document)", r["docid"])
        n_comments = r["raw_group"].count("<!--")
        if n_comments:
            comments["files"].add(r["docid"])
            comments["occ"] += n_comments
        for c in r["contribs"]:
            n_contribs += 1
            cnt = Counter(local(d.tag) for d in c.iter() if d is not c and isinstance(d.tag, str))
            for name, k in cnt.items():
                entry(name)["per"][k] += 1

    return {
        "elems": elems,
        "pis": pis,
        "comments": comments,
        "n_contribs": n_contribs,
        "total": len(rows),
        "ids": {r["docid"]: r["file_id"] for r in rows},
    }


def _flags(e: dict, total: int, rare_ok: bool) -> list:
    """[(css class, label, tooltip)] for one element entry."""
    out = []
    n = len(e["files"])
    if n < total:
        out.append(("partial", "partial", f"in {n} of {total} files"))
    if rare_ok and n <= RARE_MAX:
        out.append(("rare", "rare", f"only in {n} file{'' if n == 1 else 's'}"))
    if e.get("per") and max(e["per"]) > 1:
        out.append(("repeats", f"repeats x{max(e['per'])}", "more than one per contrib (highest count shown)"))
    if e.get("empty"):
        every = e["empty"] == e["occ"]
        out.append(
            (
                "empty",
                "empty" if every else "some empty",
                f"{e['empty']} of {e['occ']} occurrences have no text and no child element",
            )
        )
    return out


def _flags_html(flags: list) -> str:
    return "".join(
        f'<span class="flag {cls}" title="{esc_attr(tip)}">{esc(label)}</span>' for cls, label, tip in flags
    ) or '<span class="none">-</span>'


def flagged_count(inv: dict) -> int:
    total = inv["total"]
    rare_ok = total > 2 * RARE_MAX
    return sum(1 for e in inv["elems"].values() if _flags(e, total, rare_ok))


def _files_cell(files: set, total: int, ids: dict) -> str:
    n = len(files)
    if n == total:
        return f"{n}/{total}"
    names = sorted(files, key=lambda d: (ids.get(d) or d).lower())
    shown = "".join(f"<div>{esc(ids.get(d) or d)} <small>{esc(d)}</small></div>" for d in names[:40])
    more = f"<div>... +{n - 40} more</div>" if n > 40 else ""
    return f'<details><summary>{n}/{total}</summary>{shown}{more}</details>'


def _per_contrib(e: dict, n_contribs: int) -> str:
    per = e["per"]
    if not per:
        return "-"
    items = dict(per)
    zeros = n_contribs - sum(per.values())
    if zeros > 0:
        items[0] = zeros
    if len(items) > 8:
        return f"{min(items)} - {max(items)}"
    return " &middot; ".join(f"<b>{k}</b>: {v}" for k, v in sorted(items.items()))


def _attrs_html(attrs: dict, rare_ok: bool) -> str:
    if not attrs:
        return '<span class="none">-</span>'
    out = []
    for name, vals in attrs.items():
        if len(vals) <= 8:
            parts = []
            for v, n in vals.most_common():
                shown = esc(v) or "(empty)"
                if rare_ok and len(vals) > 1 and n <= RARE_MAX:
                    parts.append(f'<span class="rv" title="rare value">{shown}<small>&times;{n}</small></span>')
                else:
                    parts.append(f"{shown}<small>&times;{n}</small>")
            shown = ", ".join(parts)
        else:
            sample = ", ".join(esc(v) or "(empty)" for v, _ in vals.most_common(3))
            shown = f"{len(vals)} distinct, e.g. {sample}"
        out.append(f'<div><code class="tok">{esc(name)}</code> {shown}</div>')
    return "".join(out)


ELEM_LEGEND = (
    '<div class="legend">Flags: <span class="flag partial">partial</span> not in every file (open the file count to see which) &middot; '
    f'<span class="flag rare">rare</span> in {RARE_MAX} files or fewer &middot; '
    '<span class="flag repeats">repeats xN</span> more than one per contrib &middot; '
    '<span class="flag empty">empty</span> no text and no child element (e.g. an &lt;email&gt; that only holds a PI) &middot; '
    '<span class="rv">value</span> rare attribute value. '
    "Processing instructions and comments are listed as flags only - their values are in the contrib report.</div>"
)


def elements_block(inv: dict) -> str:
    total, nc, ids = inv["total"], inv["n_contribs"], inv["ids"]
    rare_ok = total > 2 * RARE_MAX
    rows = []
    for name, e in inv["elems"].items():
        parents = ", ".join(esc(p) for p, _ in e["parents"].most_common())
        rows.append(
            f'<tr><td><code class="tok">&lt;{esc(name)}&gt;</code></td>'
            f'<td>{_files_cell(e["files"], total, ids)}</td><td>{e["occ"]}</td>'
            f'<td>{_per_contrib(e, nc)}</td><td>{_flags_html(_flags(e, total, rare_ok))}</td>'
            f'<td>{parents}</td><td>{_attrs_html(e["attrs"], rare_ok)}</td></tr>'
        )
    pi_rows = []
    for target, e in inv["pis"].items():
        fl = _flags({"files": e["files"], "occ": e["occ"]}, total, rare_ok)
        pi_rows.append(
            f'<tr><td><code class="tok">&lt;?{esc(target)}?&gt;</code></td>'
            f'<td>{_files_cell(e["files"], total, ids)}</td><td>{e["occ"]}</td><td>{_flags_html(fl)}</td></tr>'
        )
    c = inv["comments"]
    if c["occ"]:
        fl = _flags({"files": c["files"], "occ": c["occ"]}, total, rare_ok)
        pi_rows.append(
            '<tr><td><code class="tok">&lt;!-- comment --&gt;</code></td>'
            f'<td>{_files_cell(c["files"], total, ids)}</td><td>{c["occ"]}</td><td>{_flags_html(fl)}</td></tr>'
        )
    return (
        '<div class="elems">'
        f'<h3>Elements - {len(inv["elems"])} unique names in {total} files ({nc} contribs)</h3>'
        '<table class="elem"><tr><th>Element</th><th>Files</th><th>Occurrences</th>'
        '<th>Per contrib (count: contribs)</th><th>Flags</th><th>Parent element(s)</th><th>Attributes</th></tr>'
        + "".join(rows)
        + "</table>"
        f'<h3>Processing instructions / comments - {len(inv["pis"])} PI targets</h3>'
        '<table class="elem"><tr><th>Target</th><th>Files</th><th>Occurrences</th><th>Flags</th></tr>'
        + "".join(pi_rows)
        + "</table></div>"
    )


def build_elements_report(client: str, shortcode: str, inv: dict, report_dir: Path) -> Path:
    chips = [
        ("Client", client, ""),
        ("Project shortcode", shortcode, ""),
        ("Documents", inv["total"], ""),
        ("Contribs", inv["n_contribs"], ""),
        ("Unique elements", len(inv["elems"]), ""),
        ("Flagged elements", flagged_count(inv), "warn" if flagged_count(inv) else "good"),
        ("Script version", f"v{SCRIPT_VERSION}", ""),
        ("Generated", now(), ""),
    ]
    out = report_dir / f"{safe_name(client)}_{safe_name(shortcode)}_elements_v{SCRIPT_VERSION}.html"
    out.write_text(
        page(f"{client} / {shortcode} - element list", chips, ELEM_LEGEND + elements_block(inv), legend=False),
        encoding="utf-8",
    )
    return out


# ----------------------------------------------------------------- rendering

def esc(s: str) -> str:
    return html.escape(s, quote=False)


def esc_attr(s: str) -> str:
    return html.escape(s, quote=True).replace("\n", "&#10;")


def chunk(s: str | None) -> str:
    """Collapse indentation whitespace; drop whitespace-only chunks between tags."""
    if not s or not s.strip(" \t\r\n"):
        return ""
    return esc(WS_RE.sub(" ", s))


def marker(tip: str) -> str:
    return f'<span class="pi miss" title="{esc_attr(tip)}">&#9888;</span>'


def render_pi(pi: ET.Element, ctx: Ctx | None) -> str:
    value = pi_value(pi)
    if value is None:
        return ""
    out = esc(value)
    tip = ctx.pi_bad.get(id(pi)) if ctx else None
    if tip:
        return f'<span class="pi bad" title="{esc_attr(tip)}">{out or "&#9888;"}</span>'
    return f'<span class="pi">{out}</span>' if HIGHLIGHT_PI else out


def render(el: ET.Element, ctx: Ctx | None = None) -> str:
    out = [chunk(el.text)]
    for child in el:
        if child.tag is PI:
            out.append(render_pi(child, ctx))
        elif isinstance(child.tag, str):
            if ctx:
                out += [marker(t) for t in ctx.miss_before.get(id(child), [])]
            inner = render(child, ctx)
            wrap = INLINE_TAGS.get(local(child.tag))
            out.append(f"<{wrap}>{inner}</{wrap}>" if wrap else inner)
        out.append(chunk(child.tail))
    if ctx:
        out += [marker(t) for t in ctx.miss_end.get(id(el), [])]
    return "".join(out)


# --------------------------------------------------------------------- pages

CSS = """
*{box-sizing:border-box}
body{font-family:system-ui,Segoe UI,Arial,sans-serif;margin:0;color:#1f2328}
header#top{position:sticky;top:0;z-index:5;background:#fff;border-bottom:1px solid #d0d7de;
  padding:12px 24px;display:flex;flex-wrap:wrap;align-items:center;gap:8px 20px}
header#top .ttl{font-size:18px;font-weight:700}
.chips{display:flex;flex-wrap:wrap;gap:6px;flex:1}
.chip{font-size:12px;background:#f6f8fa;border:1px solid #d0d7de;border-radius:999px;padding:2px 10px;color:#57606a}
.chip b{color:#1f2328;font-weight:600}
.chip.warn{background:#ffebe9;border-color:#f0625d;color:#b42318}
.chip.good{background:#dafbe1;border-color:#4ac26b;color:#1a7f37}
main{padding:16px 24px 32px}
.legend{font-size:12px;color:#57606a;margin-bottom:12px}
.legend .pi{padding:0 4px}
table{border-collapse:separate;border-spacing:0;width:100%;font-size:14px;
  border-left:1px solid #d0d7de;border-top:1px solid #d0d7de}
th,td{border-right:1px solid #d0d7de;border-bottom:1px solid #d0d7de;padding:8px 10px;
  text-align:left;vertical-align:top}
th{background:#f6f8fa}
table.files th{position:sticky;top:var(--hh,64px);z-index:2}
tr:nth-child(even) td{background:#fafbfc}
td.fid{white-space:nowrap;font-weight:600}
td.na{color:#9aa4ad}
td.err{color:#b42318;background:#fff1f0}
td.docid{font-family:ui-monospace,Consolas,monospace;font-size:12px;color:#57606a;word-break:break-all}
td.chk ul{margin:0;padding-left:16px;font-size:12px;color:#b42318}
td.chk .ok{color:#1a7f37;font-size:12px}
.pi{background:#fff3b0;border-radius:2px}
.pi.bad{background:#ffd8d3;outline:1px solid #f0625d}
.pi.miss{background:#ffd8d3;color:#b42318;font-weight:700;padding:0 2px;outline:1px solid #f0625d}
.badge{display:inline-block;margin-left:6px;font-size:11px;font-weight:600;color:#b42318;
  background:#ffebe9;border:1px solid #f0625d;border-radius:999px;padding:0 7px;cursor:help}
.toggle{display:inline-flex;border:1px solid #d0d7de;border-radius:6px;overflow:hidden}
.toggle button{border:0;background:#fff;padding:6px 14px;font-size:13px;cursor:pointer;color:#1f2328}
.toggle button.on{background:#0969da;color:#fff}
body[data-view=preview] .v-raw{display:none}
body[data-view=raw] .v-preview{display:none}
pre.raw{margin:0;font:12px/1.45 ui-monospace,Consolas,monospace;white-space:pre-wrap;overflow-wrap:anywhere;tab-size:2}
sup{font-size:.75em}
a{color:#0969da;text-decoration:none} a:hover{text-decoration:underline}
tr[id]{scroll-margin-top:calc(var(--hh,64px) + 44px)}
tr:target td{background:#fff8c5!important}
.tags{margin-top:6px;display:flex;gap:4px;flex-wrap:wrap}
.tag{font-size:11px;border:1px solid #d0d7de;border-radius:4px;padding:0 5px;color:#57606a;background:#fff}
.tag.bad{border-color:#f0625d;background:#ffebe9;color:#b42318;font-weight:600}
.hlinks{display:flex;gap:8px}
.hlinks a{font-size:13px;border:1px solid #d0d7de;border-radius:6px;padding:4px 10px;background:#fff}
.elems{padding:4px 14px 14px}
.elems h3{font-size:14px;margin:16px 0 6px}
.elems small{color:#57606a}
table.elem{width:100%;margin-bottom:16px}
table.elem th{position:static}
table.elem td{vertical-align:top;font-size:13px}
table.elem details{font-size:12px}
table.elem summary{cursor:pointer}
.part{background:#fff8c5;border:1px solid #d4a72c;border-radius:999px;padding:0 6px;font-size:11px;color:#7d4e00}
.pv{margin-top:6px;padding:6px 8px;background:#fff;border:1px dashed #d0d7de;border-radius:6px;font-size:13px}
.pv-l{display:block;font-size:11px;color:#57606a;margin-bottom:2px}
.okbox{margin-bottom:20px;padding:10px 14px;border:1px solid #4ac26b;background:#dafbe1;color:#1a7f37;border-radius:8px;font-size:13px}
table.fix{width:calc(100% - 24px);margin:12px}
table.fix th{position:static}
table.fix td{font-size:13px;vertical-align:top}
table.fix td.det{font-size:12px}
.toolbar{margin:0 0 10px;font-size:13px}
table.files.only tr[data-row]:not([data-issue]){display:none}
.flag{display:inline-block;margin:1px 3px 1px 0;font-size:11px;border-radius:999px;padding:0 7px;border:1px solid #d0d7de;background:#f6f8fa;color:#57606a;cursor:help}
.flag.partial{background:#fff8c5;border-color:#d4a72c;color:#7d4e00}
.flag.rare{background:#fbefff;border-color:#c297ff;color:#6e40c9}
.flag.repeats{background:#ddf4ff;border-color:#54aeff;color:#0550ae}
.flag.empty{background:#eaeef2;border-color:#8c959f;color:#424a53}
.rv{background:#fbefff;border-radius:3px;padding:0 3px;color:#6e40c9}
.tag.xref{background:#ddf4ff;border-color:#54aeff;color:#0550ae}
.xg{margin-bottom:14px}
.xg-h{display:flex;gap:8px;align-items:baseline;margin:0 0 6px;font-size:13px}
.xg-h b{background:#ddf4ff;border:1px solid #54aeff;border-radius:999px;padding:0 9px;color:#0550ae}
.xg-h .cnt{color:#57606a;font-size:12px}
details.stats{margin-bottom:20px;border:1px solid #d0d7de;border-radius:8px;background:#fff}
details.stats>summary{cursor:pointer;font-weight:600;padding:10px 14px;background:#f6f8fa;border-radius:8px}
details.stats>summary .sub{font-weight:400;color:#57606a;font-size:12px;margin-left:8px}
table.stat{width:calc(100% - 24px);margin:12px}
table.stat th{position:static}
table.stat th.rl{white-space:nowrap;width:1%}
table.stat td{background:#fff!important;width:33%}
.pat{border:1px solid #d0d7de;border-radius:6px;padding:8px;margin-bottom:8px;background:#fff}
.pat.minor{border-color:#f0625d;background:#fff8f7}
.pat.na{background:#f6f8fa}
.pat-h{font-size:13px;margin-bottom:6px;display:flex;gap:8px;align-items:baseline;flex-wrap:wrap}
.pat-h .cnt{font-weight:700}
.pat-h .pct{color:#57606a;font-size:12px}
.pat-h .lbl{font-size:11px;padding:0 6px;border-radius:999px;border:1px solid #d0d7de;color:#57606a}
.pat.minor .lbl{border-color:#f0625d;color:#b42318}
ol.seq{margin:0 0 6px;padding-left:22px;font-size:12px}
ol.seq li{margin:2px 0}
ol.seq li.none{list-style:none;color:#9aa4ad;margin-left:-22px}
ol.seq li.bad code{background:#ffd8d3;outline:1px solid #f0625d}
code.tok{background:#eef1f4;border-radius:3px;padding:0 4px;font:12px ui-monospace,Consolas,monospace;white-space:pre-wrap}
.diff{font-size:12px;margin:4px 0 6px}
.diff .k{font-size:11px;text-transform:uppercase;margin-right:4px}
.diff .k.differs{color:#9a6700}.diff .k.missing{color:#b42318}.diff .k.extra{color:#8250df}
.pat details{font-size:12px}
.pat summary{cursor:pointer;color:#57606a}
.frow{display:flex;gap:8px;align-items:baseline;padding:2px 0}
.frow a{font-weight:600;white-space:nowrap}
.frow .did{font:11px ui-monospace,Consolas,monospace;color:#57606a;word-break:break-all}
"""

TOGGLE = (
    '<div class="toggle" role="group" aria-label="Column view">'
    '<button type="button" data-view="preview" class="on">Preview HTML</button>'
    '<button type="button" data-view="raw">Raw XML</button></div>'
)

LEGEND = (
    '<div class="legend"><span class="pi">text</span> restored from pistart &middot; '
    '<span class="pi bad">text</span> differs from the most common value at the same position &middot; '
    '<span class="pi miss">&#9888;</span> pistart missing where other files have it</div>'
)

JS = """<script>
(function () {
  var h = document.getElementById('top');
  function fit() { document.documentElement.style.setProperty('--hh', h.offsetHeight + 'px'); }
  fit(); window.addEventListener('resize', fit); window.addEventListener('load', fit);
  var cb = document.getElementById('onlyIssues');
  if (cb) {
    cb.addEventListener('change', function () {
      document.querySelector('table.files').classList.toggle('only', cb.checked);
    });
  }
  document.querySelectorAll('.toggle button').forEach(function (b) {
    b.addEventListener('click', function () {
      document.body.setAttribute('data-view', b.dataset.view);
      document.querySelectorAll('.toggle button').forEach(function (x) {
        x.classList.toggle('on', x === b);
      });
    });
  });
})();
</script>"""


def page(title: str, chips: list, body: str, toggle: bool = False, links=None, legend: bool = True) -> str:
    """chips: list of (label, value, style) with style in '', 'warn', 'good'."""
    chips_html = "".join(
        f'<span class="chip {style}"><b>{esc(label)}</b> {esc(str(value))}</span>'
        for label, value, style in chips
    )
    links_html = "".join(f'<a href="{esc_attr(h)}">{esc(l)}</a>' for l, h in (links or []))
    return (
        '<!DOCTYPE html>\n<html lang="en"><head><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width, initial-scale=1">'
        f"<title>{esc(title)}</title><style>{CSS}</style></head>"
        '<body data-view="preview">'
        f'<header id="top"><div class="ttl">{esc(title)}</div>'
        f'<div class="chips">{chips_html}</div><div class="hlinks">{links_html}</div>{TOGGLE if toggle else ""}</header>'
        f"<main>{LEGEND if legend else ''}{body}</main>{JS}</body></html>"
    )


def issue_chip(n: int) -> tuple:
    return ("PI issues (all contribs)", n, "warn" if n else "good")


def now() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M")


def write_doc_outputs(row: dict, client: str, shortcode: str, ctx: Ctx, issues: list):
    folder: Path = row["folder"]
    (folder / OUT_XML).write_text(row["raw_group"], encoding="utf-8")

    by_n: dict = defaultdict(list)
    for i in issues:
        by_n[i["n"]].append(i["text"])

    trs = []
    for n, c in enumerate(row["contribs"], 1):
        if by_n[n]:
            chk = "<ul>" + "".join(f"<li>{esc(t)}</li>" for t in by_n[n]) + "</ul>"
        else:
            chk = '<span class="ok">OK</span>'
        trs.append(f'<tr><td>{n}</td><td>{render(c, ctx)}</td><td class="chk">{chk}</td></tr>')

    body = (
        '<table class="files"><tr><th>#</th><th>Contrib</th><th>PI check (all contribs)</th></tr>'
        + "".join(trs)
        + "</table>"
    )
    chips = [
        ("Docid", row["docid"], ""),
        ("Client", client, ""),
        ("Shortcode", shortcode, ""),
        ("Contribs", len(row["contribs"]), ""),
        issue_chip(len(issues)),
        ("Script version", f"v{SCRIPT_VERSION}", ""),
        ("Generated", now(), ""),
    ]
    title = row["file_id"] or row["docid"]
    (folder / OUT_HTML).write_text(page(title, chips, body), encoding="utf-8")


def pick_cells(contribs, raws, ctx: Ctx) -> list:
    """
    first / last-before / last as (preview_html, raw_xml) pairs (see role_index),
    None where the document has no contrib for that column.
    """
    n = len(contribs)

    def cell(i):
        raw = raws[i] if i < len(raws) else "(raw xml not available)"
        return render(contribs[i], ctx), raw

    out = []
    for role, _ in ROLES:
        i = role_index(n, role)
        out.append(cell(i) if i is not None else None)
    return out


def has_issue(r: dict) -> bool:
    return bool(r["issues"]) or any(n not in (None, 1) for n in r["pat"].values())


def build_report(client: str, shortcode: str, rows: list[dict], report_dir: Path, stats,
                 entries: list, elements_file=None):
    rows = sorted(rows, key=lambda r: (r["file_id"] or r["docid"]).lower())
    trs = []
    for r in rows:
        fid = esc(r["file_id"] or r["docid"])
        if r["preview_rel"]:
            fid = f'<a href="{esc(r["preview_rel"])}">{fid}</a>'
        if r["issues"]:
            tips = [i["text"] for i in r["issues"][:8]]
            if len(r["issues"]) > 8:
                tips.append(f"... +{len(r['issues']) - 8} more")
            fid += (
                f' <span class="badge" title="{esc_attr("PI check on all contribs:" + chr(10) + chr(10).join(tips))}">'
                f'&#9888; {len(r["issues"])}</span>'
            )
        did = f'<td class="docid">{esc(r["docid"])}</td>'
        rid = esc(row_id(r["docid"]))
        if r["error"]:
            trs.append(
                f'<tr id="{rid}" data-row data-issue><td class="fid">{fid}</td>{did}'
                f'<td class="err" colspan="3">{esc(r["error"])}</td></tr>'
            )
            continue
        cells = "".join(
            (
                f'<td><div class="v-preview">{c[0]}</div>'
                f'<div class="v-raw"><pre class="raw">{esc(c[1])}</pre></div>'
                f'{cell_tags(r, role)}</td>'
            )
            if c
            else f'<td class="na" title="{esc_attr(na_title(len(r["contribs"])))}">-</td>'
            for (role, _), c in zip(ROLES, r["cells"])
        )
        flag = " data-issue" if has_issue(r) else ""
        trs.append(f'<tr id="{rid}" data-row{flag}><td class="fid">{fid}</td>{did}{cells}</tr>')

    good = [r for r in rows if r["contribs"]]
    body = (
        fix_html(entries)
        + stats_html(stats)
        + allcheck_html(good)
        + '<div class="toolbar"><label><input type="checkbox" id="onlyIssues"> '
        "Only files with issues (off-pattern or PI check)</label></div>"
        + '<table class="files"><tr><th>File ID</th><th>Docid</th>'
        "<th>First contrib</th><th>Last before</th><th>Last contrib</th></tr>"
        + "".join(trs)
        + "</table>"
    )

    n_issues = sum(len(r["issues"]) for r in good)
    off = off_pattern_rows(good)
    chips = [
        ("Client", client, ""),
        ("Project shortcode", shortcode, ""),
        ("Documents", len(rows), ""),
        ("Contribs checked", sum(len(r["contribs"]) for r in good), ""),
        ("Off-pattern files", f"{len(off)}/{len(good)}", "warn" if off else "good"),
        issue_chip(n_issues),
    ]
    failed = len(rows) - len(good)
    if failed:
        chips.append(("Failed docs", failed, "warn"))
    chips.append(("Script version", f"v{SCRIPT_VERSION}", ""))
    chips.append(("Generated", now(), ""))

    out = report_dir / f"{safe_name(client)}_{safe_name(shortcode)}_contrib_v{SCRIPT_VERSION}.html"
    out.write_text(
        page(
            f"{client} / {shortcode} - contrib report",
            chips,
            body,
            toggle=True,
            links=[("Element list", elements_file)] if elements_file else None,
        ),
        encoding="utf-8",
    )
    return out, len(off)


def write_issues_csv(client: str, shortcode: str, entries: list, good: list, report_dir: Path) -> Path:
    """All findings of the contrib report, one line each (opens in Excel)."""
    out = report_dir / f"{safe_name(client)}_{safe_name(shortcode)}_issues_v{SCRIPT_VERSION}.csv"
    with open(out, "w", newline="", encoding="utf-8-sig") as f:
        w = csv.writer(f)
        w.writerow(["file_id", "docid", "check", "column", "xref_group", "kind", "pattern", "detail"])
        for e in entries:
            r = e["row"]
            w.writerow(
                [r["file_id"], r["docid"], "pattern", e["role"], e["xref"], e["kind"],
                 f"pattern-{e['pattern']}", " | ".join(e["plain"])]
            )
        for r in sorted(good, key=lambda r: (r["file_id"] or r["docid"]).lower()):
            for i in r["issues"]:
                w.writerow([r["file_id"], r["docid"], "all-contribs", f"contrib #{i['n']}", "", i["kind"], "", i["text"]])
    return out


def print_top_issues(entries: list, good: list, limit: int = 5):
    n_all = sum(len(r["issues"]) for r in good)
    if not entries and not n_all:
        print("[ISSUES] none")
        return
    n_files = len({e["row"]["docid"] for e in entries})
    print(f"[ISSUES] {len(entries)} pattern finding(s) in {n_files} file(s); {n_all} PI issue(s) on all contribs")
    for e in entries[:limit]:
        r = e["row"]
        detail = e["plain"][0] if e["plain"] else ""
        print(f"    {r['file_id'] or r['docid']}: {e['role']} / {e['xref']} / {e['kind']} - {detail}")
    if len(entries) > limit:
        print(f"    ... +{len(entries) - limit} more (see the report / csv)")


# ------------------------------------------------------------- one document

def read_doc(base: Path, docid: str, item: dict, meta: dict) -> dict:
    """Read + parse one document. Never raises; problems go into row['error']."""
    row = {
        "docid": docid,
        "file_id": meta.get("file-id", ""),
        "folder": doc_folder(base, docid, item, meta),
        "preview_rel": "",
        "cells": None,
        "error": None,
        "contribs": None,
        "raws": [],
        "gaps": [],
        "raw_group": "",
        "group_root": None,
        "issues": [],
        "xkeys": [],
        "cmp_cls": [],
        "xk": {},
        "hits": [],
        "seqs": [],
        "pat": {},
    }
    folder = row["folder"]
    if not folder.is_dir():
        row["error"] = f"folder not found: {folder}"
        print(f"[MISSING] {docid} - {row['error']}")
        return row

    src, raw = extract_contrib_groups(folder, base, item)
    if not raw:
        row["error"] = "no <contrib-group> found in any xml in folder"
        print(f"[NO CONTRIB] {docid} - {row['error']}")
        return row

    try:
        group_root = parse_group(raw)
        contribs = list(group_root.iter("contrib"))
    except ET.ParseError as e:
        row["error"] = f"contrib-group parse error: {e}"
        print(f"[FAILED] {docid} - {row['error']}")
        return row

    if not contribs:
        row["error"] = "<contrib-group> has no <contrib>"
        print(f"[EMPTY] {docid} - {row['error']}")
        return row

    raws = raw_contribs(raw)
    if len(raws) != len(contribs):
        print(f"[WARN] {docid} - raw/parsed contrib count differs ({len(raws)} vs {len(contribs)})")

    row["contribs"] = contribs
    row["raws"] = raws
    row["raw_group"] = raw
    row["group_root"] = group_root
    row["src"] = src.name
    row["gaps"] = [analyze(c) for c in contribs]
    n = len(contribs)
    row["xkeys"] = [xref_key(c) for c in contribs]
    row["cmp_cls"] = [(contrib_class(i, n), row["xkeys"][i]) for i in range(n)]
    row["hits"] = [pattern_hits(g) for g in row["gaps"]]
    row["seqs"] = [pi_sequences(h) for h in row["hits"]]
    return row


# ------------------------------------------------------ one client + shortcode

def process_group(base: Path, docs: dict, metas: dict, client: str, shortcode: str, docids: list) -> dict:
    """Build per-doc outputs, the contrib report, the element list and the issues csv."""
    report_dir = base / REPORT_DIR / RUN_DTD
    report_dir.mkdir(parents=True, exist_ok=True)

    rows = [read_doc(base, d, docs[d], metas[d]) for d in docids]
    good = [r for r in rows if r["contribs"]]

    expected = expected_values(
        (cls, gl) for r in good for cls, gl in zip(r["cmp_cls"], r["gaps"])
    )
    stats = build_stats(good) if good else None
    entries = fix_entries(stats)

    inv = build_inventory(good) if good else None
    elements_out = None
    if inv:
        elements_out = build_elements_report(client, shortcode, inv, report_dir)
        print(f"[ELEMENTS] {elements_out.relative_to(base)} ({len(inv['elems'])} elements, "
              f"{flagged_count(inv)} flagged)")

    total_issues = 0
    for r in good:
        ctx, issues = build_ctx(r["gaps"], r["cmp_cls"], expected)
        r["issues"] = issues
        write_doc_outputs(r, client, shortcode, ctx, issues)
        r["cells"] = pick_cells(r["contribs"], r["raws"], ctx)
        r["preview_rel"] = Path(os.path.relpath(r["folder"] / OUT_HTML, report_dir)).as_posix()
        total_issues += len(issues)
        tag = f", {len(issues)} PI issue(s)" if issues else ""
        print(f"[OK] {r['docid']} ({r['src']}) - {len(r['contribs'])} contribs{tag}")

    out, n_off = build_report(
        client, shortcode, rows, report_dir, stats, entries, elements_out.name if elements_out else None
    )
    print(f"[REPORT] {out.relative_to(base)} ({len(rows)} docs, {n_off} off-pattern)")
    csv_out = write_issues_csv(client, shortcode, entries, good, report_dir)
    print(f"[ISSUES CSV] {csv_out.relative_to(base)}")
    print_top_issues(entries, good)

    return {
        "generated_at": now(),
        "version": SCRIPT_VERSION,
        "report": out.relative_to(base).as_posix(),
        "elements_report": elements_out.relative_to(base).as_posix() if elements_out else None,
        "issues_csv": csv_out.relative_to(base).as_posix(),
        "unique_elements": len(inv["elems"]) if inv else 0,
        "flagged_elements": flagged_count(inv) if inv else 0,
        "documents": len(rows),
        "failed": len(rows) - len(good),
        "off_pattern_files": n_off,
        "pattern_findings": len(entries),
        "consistency_issues": total_issues,
        "docids": {
            r["docid"]: {
                "file-id": r["file_id"],
                "contribs": len(r["contribs"]) if r["contribs"] else 0,
                "status": "ok" if r["contribs"] else f"error: {r['error']}",
            }
            for r in rows
        },
    }


# ------------------------------------------------ what is in meta / what is done

def dtd_of(item: dict, meta: dict) -> str:
    return meta.get("dtd") or item.get("folder", "").split("/", 1)[0]


def build_index(docs: dict, metas: dict) -> dict:
    """{client: {shortcode: [docid, ...]}} for RUN_DTD documents only."""
    index: dict = {}
    for docid, meta in metas.items():
        item = docs.get(docid)
        if item is None or dtd_of(item, meta) != RUN_DTD:
            continue
        client = meta.get("client") or "unknown"
        shortcode = meta.get("project-shortcode") or "unknown"
        index.setdefault(client, {}).setdefault(shortcode, []).append(docid)
    return index


def load_done(base: Path) -> dict:
    p = base / DONE_NAME
    return load_json(p) if p.exists() else {}


def save_done(base: Path, data: dict):
    p = base / DONE_NAME
    tmp = p.with_suffix(".json.tmp")
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    os.replace(tmp, p)  # never leaves a half written file behind


def done_entry(done: dict, client: str, shortcode: str):
    return done.get(RUN_DTD, {}).get(client, {}).get(shortcode)


def status_of(done: dict, client: str, shortcode: str, docids: list):
    """('new'|'update'|'done', number of docids not recorded yet)"""
    e = done_entry(done, client, shortcode)
    if not e:
        return "new", 0
    seen = e.get("docids", {})
    fresh = [d for d in docids if d not in seen]
    if fresh:
        return "update", len(fresh)
    if e.get("version") != SCRIPT_VERSION:  # generated by an older script version
        return "update", 0
    return "done", 0


# ----------------------------------------------------------------- questions

def parse_choice(raw: str, options: list):
    """'1,3' or 'LWW plos' -> matching option names, None if anything is unknown."""
    lookup = {o.lower(): o for o in options}
    out = []
    for part in re.split(r"[,\s]+", raw.strip()):
        if not part:
            continue
        if part.isdigit() and 1 <= int(part) <= len(options):
            name = options[int(part) - 1]
        elif part.lower() in lookup:
            name = lookup[part.lower()]
        else:
            return None
        if name not in out:
            out.append(name)
    return out


def cnt(n: int, word: str = "doc") -> str:
    return f"{n} {word}{'' if n == 1 else 's'}"


def status_note(done: dict, client: str, shortcode: str, docids: list) -> str:
    st, n = status_of(done, client, shortcode, docids)
    if st == "new":
        return "not filled"
    if st == "update":
        if n == 0:
            return "update (older script version, regenerate)"
        return f"update (+{n} new doc{'' if n == 1 else 's'})"
    e = done_entry(done, client, shortcode)
    bad = f", {e['failed']} failed" if e.get("failed") else ""
    return f"filled {e.get('generated_at', '')}{bad}"


def print_overview(docs: dict, metas: dict, index: dict, done: dict):
    """Unique counts Clients -> Shortcodes and whether each is already filled."""
    clients = sorted(index, key=str.lower)
    pairs = [(c, sc) for c in clients for sc in sorted(index[c], key=str.lower)]
    n_docs = sum(len(v) for scs in index.values() for v in scs.values())
    unique_sc = {sc for _, sc in pairs}
    states = Counter(status_of(done, c, sc, index[c][sc])[0] for c, sc in pairs)

    extra = "" if len(unique_sc) == len(pairs) else f"  ({len(unique_sc)} unique shortcode names)"
    print(f"\n{RUN_DTD} overview:  {len(clients)} clients | {len(pairs)} shortcodes | {n_docs} docs{extra}")
    print(
        f"  filled: {states['done']}  |  not filled: {states['new']}  |  "
        f"update (new docs): {states['update']}"
    )
    print()
    for c in clients:
        scs = index[c]
        filled = sum(status_of(done, c, sc, ids)[0] == "done" for sc, ids in scs.items())
        docs_c = sum(len(v) for v in scs.values())
        print(f"  {c}   {len(scs)} shortcodes, {docs_c} docs   ({filled}/{len(scs)} filled)")
        for sc in sorted(scs, key=str.lower):
            print(f"      {sc:<14}{len(scs[sc]):>6} docs   [{status_note(done, c, sc, scs[sc])}]")

    notes = []
    others = Counter(
        dtd_of(docs[d], m) or "?" for d, m in metas.items() if d in docs and dtd_of(docs[d], m) != RUN_DTD
    )
    if others:
        notes.append("not " + RUN_DTD + ": " + ", ".join(f"{k} {cnt(v)}" for k, v in sorted(others.items())))
    no_meta = sum(1 for d in docs if d not in metas)
    if no_meta:
        notes.append(f"{cnt(no_meta)} without a {META_NAME} entry")
    blank = sum(len(v) for sc_map in index.values() for sc, v in sc_map.items() if sc == "unknown")
    blank += sum(len(v) for c, sc_map in index.items() if c == "unknown" for v in sc_map.values())
    if blank:
        notes.append(f"{cnt(blank)} with a blank client or shortcode (grouped as 'unknown')")
    if notes:
        print("\n  ignored / check: " + "; ".join(notes))


def choose_clients(index: dict, done: dict) -> list:
    clients = sorted(index, key=str.lower)
    print(f"\n{RUN_DTD} clients:")
    for i, c in enumerate(clients, 1):
        scs = index[c]
        pending = sum(status_of(done, c, sc, ids)[0] != "done" for sc, ids in scs.items())
        n_docs = sum(len(v) for v in scs.values())
        tail = f"{pending} to generate" if pending else "all filled"
        print(f"  {i}) {c:<14}{len(scs):>4} shortcodes{n_docs:>8} docs   {tail}")
    while True:
        raw = input("Client (number/name, comma for several, 'all'): ").strip()
        if raw.lower() == "all":
            return clients
        picked = parse_choice(raw, clients)
        if picked:
            return picked
        print("  not recognised, try again")


def choose_shortcodes(clients: list, index: dict, done: dict) -> list:
    """Return the (client, shortcode) pairs to generate."""
    scs = None
    if len(clients) == 1:
        c = clients[0]
        scs = sorted(index[c], key=str.lower)
        print(f"\n{RUN_DTD} / {c} shortcodes:")
        for i, sc in enumerate(scs, 1):
            note = status_note(done, c, sc, index[c][sc])
            print(f"  {i}) {sc:<14}{len(index[c][sc]):>6} docs   [{note}]")
        prompt = (
            "Shortcode (number/name, comma for several; Enter = all not filled/updated; "
            "'all' = regenerate everything): "
        )
    else:
        prompt = (
            f"Shortcodes for {', '.join(clients)} (Enter = all not filled/updated; "
            "'all' = regenerate everything): "
        )

    while True:
        raw = input(prompt).strip()
        low = raw.lower()
        if low in ("", "new", "all"):
            pairs = []
            for c in clients:
                for sc in sorted(index[c], key=str.lower):
                    st, _ = status_of(done, c, sc, index[c][sc])
                    if low == "all" or st != "done":
                        pairs.append((c, sc))
            return pairs
        picked = parse_choice(raw, scs) if scs else None
        if picked:
            pairs = []
            for sc in picked:
                st, _ = status_of(done, clients[0], sc, index[clients[0]][sc])
                if st == "done":
                    ans = input(f"  {sc} is already filled. Regenerate? [y/N]: ").strip().lower()
                    if ans != "y":
                        continue
                pairs.append((clients[0], sc))
            return pairs
        print("  not recognised, try again")


# ---------------------------------------------------------------------- main

def ask_delay(label: str, default: float) -> float:
    while True:
        raw = input(f"{label} in seconds [{default:g}]: ").strip()
        if not raw:
            return default
        try:
            v = float(raw)
            if v >= 0:
                return v
        except ValueError:
            pass
        print("  enter a number of seconds (0 = no pause)")


def pause(seconds: float, why: str):
    if seconds > 0:
        print(f"  ... pausing {seconds:g}s before {why} (Ctrl+C to stop)")
        time.sleep(seconds)


def main():
    base = Path(input("Project Folder: ").strip().strip('"'))
    if not (base / DOCS_NAME).exists() or not (base / META_NAME).exists():
        print(f"Missing {DOCS_NAME} or {META_NAME} in {base}")
        return

    docs = load_json(base / DOCS_NAME)
    metas = load_json(base / META_NAME)
    index = build_index(docs, metas)
    if not index:
        print(f"No {RUN_DTD} documents found in {META_NAME} (is the 'dtd' field filled in?)")
        return

    done = load_done(base)
    print_overview(docs, metas, index, done)

    clients = choose_clients(index, done)
    pairs = choose_shortcodes(clients, index, done)  # already ordered client -> shortcode
    if not pairs:
        print("\nNothing to generate (everything selected is already in "
              f"{DONE_NAME}; pick it by number or type 'all' to redo).")
        return

    total = len(pairs)
    delay_sc = delay_cl = 0.0
    if total > 1:
        print()
        delay_sc = ask_delay("Pause between shortcodes", DELAY_SHORTCODE_SEC)
        if len({c for c, _ in pairs}) > 1:
            delay_cl = ask_delay("Pause between clients", DELAY_CLIENT_SEC)

    left: Counter = Counter(c for c, _ in pairs)
    finished = []
    try:
        for i, (client, shortcode) in enumerate(pairs, 1):
            ids = index[client][shortcode]
            print(f"\n=== [{i}/{total}] {RUN_DTD} / {client} / {shortcode} ({cnt(len(ids))}) ===")
            entry = process_group(base, docs, metas, client, shortcode, ids)
            if entry["failed"] == entry["documents"]:
                print(f"[SKIP RECORD] every document failed, {shortcode} not marked as filled")
            else:
                done.setdefault(RUN_DTD, {}).setdefault(client, {})[shortcode] = entry
                save_done(base, done)  # recorded BEFORE the pause, so a stop keeps it
            finished.append((client, shortcode, entry))

            left[client] -= 1
            if left[client] == 0:
                print(f"[CLIENT COMPLETE] {client}")
            if i < total:
                nxt_client, nxt_sc = pairs[i]
                if nxt_client != client:
                    pause(delay_cl, f"client {nxt_client}")
                else:
                    pause(delay_sc, f"shortcode {nxt_client}/{nxt_sc}")
    except KeyboardInterrupt:
        print("\nStopped by user. Finished shortcodes are already saved in " + DONE_NAME)

    print(f"\nSummary ({len(finished)}/{total} shortcodes processed):")
    for client, shortcode, e in finished:
        print(
            f"  {client} / {shortcode:<12} {e['documents']:>5} docs  {e['failed']:>3} failed  "
            f"{e['off_pattern_files']:>3} off-pattern  -> {e['report']}"
        )
    print(f"Progress saved in {DONE_NAME}")


if __name__ == "__main__":
    main()
